'use strict'

export default  {
  
  // TWEET ACTIONS
  SELECT_TWEET: 'SELECT_TWEET',
  LOAD_TWEETS: 'LOAD_TWEETS',
  ADD_TWEET: 'ADD_TWEETS',
  LOAD_HASHTAGS: 'LOAD_HASHTAGS',

  // USER ACTIONS
  SELECT_USER: 'SELECT_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  CREATE_USER: 'CREATE_USER',
  CHECK_LOGGED_IN_USER: 'CHECK_LOGGED_IN_USER',
  UPDATE_USERNAME_INPUT: 'UPDATE_USERNAME_INPUT',
  UPDATE_PASSWORD_INPUT: 'UPDATE_PASSWORD_INPUT',

  // UI
  CHANGE_PROMPT: 'CHANGE_PROMPT',
  CHANGE_NAVIGATION_LINKS: 'CHANGE_NAVIGATION_LINKS',
  DISPLAY_SIGNUP: 'DISPLAY_SIGNUP'
}



